--INSERT INTO REPUESTO (id_repuesto, cantidad, descripcion, nombre, valor) values (4, 8, 'Pastillas De Freno Brembo Traseras Ford Fiesta St', 'Pastas Frenos', 170000)
--INSERT INTO REPUESTO (id_repuesto, cantidad, descripcion, nombre, valor) values (5, 12, 'Llanta Timsun 90-90-18', 'Llanta', 115000)
--INSERT INTO REPUESTO (id_repuesto, cantidad, descripcion, nombre, valor) values (1, 5, 'Bateria motocicleta', 'Bateria', 40000)
--INSERT INTO REPUESTO (id_repuesto, cantidad, descripcion, nombre, valor) values (2, 3, 'Bateria carro', 'Bateria', 140000)
--INSERT INTO REPUESTO (id_repuesto, cantidad, descripcion, nombre, valor) values (3, 25, 'Aceite YAMALUBE 4t', 'Aceite', 22000)
--INSERT INTO REPUESTO (id_repuesto, cantidad, descripcion, nombre, valor) values (6, 25, 'Nuevo repuesto', 'Ejemplo', 10294)
INSERT INTO PERSONA(id_persona, apellidos, correo, direccion, nombre, telefono) values (1, 'Ramirez Gonzales', 'ramirez1@gmail.com', 'cll #4', 'Raul', 0003344568)
INSERT INTO PERSONA(id_persona, apellidos, correo, direccion, nombre, telefono) values (2, 'Martinez Garzon', 'mgarzon@gmail.com', 'cll #5', 'Gabriel', 0003342958)
INSERT INTO PERSONA(id_persona, apellidos, correo, direccion, nombre, telefono) values (3, 'Morales Alzate', 'moralesA@gmail.com', 'cll #6', 'Arturo', 0001586943)
INSERT INTO PERSONA(id_persona, apellidos, correo, direccion, nombre, telefono) values (4, 'Galeano Amaya', 'GaliAma@gmail.com', 'cll #7', 'Julian', 0004674568)
INSERT INTO PERSONA(id_persona, apellidos, correo, direccion, nombre, telefono) values (5, 'Pinilla Forero', 'espini@gmail.com', 'cll #8', 'Jonathan', 0001894568)
INSERT INTO PERSONA(id_persona, apellidos, correo, direccion, nombre, telefono) values (6, 'Ramirez Amaya', 'ramiama@gmail.com', 'cll #9', 'luis', 0001894568)
INSERT INTO HISTORIAL(id_historial) values (1)
--INSERT INTO VEHICULO(id_vehiculo,estado,placa,tipo_vehiculo,id_historial) values (1,true, 'LOP56C', 'Motocicleta', 1)


