INSERT INTO REPUESTO (id_repuesto, cantidad, descripcion, nombre, valor) values (1, 5, 'Bateria motocicleta', 'Bateria', 40000)
INSERT INTO REPUESTO (id_repuesto, cantidad, descripcion, nombre, valor) values (2, 3, 'Bateria carro', 'Bateria', 140000)
INSERT INTO REPUESTO (id_repuesto, cantidad, descripcion, nombre, valor) values (3, 25, 'Aceite YAMALUBE 4t', 'Aceite', 22000)
INSERT INTO REPUESTO (id_repuesto, cantidad, descripcion, nombre, valor) values (4, 8, 'Pastillas De Freno Brembo Traseras Ford Fiesta St', 'Pastas Frenos', 170000)
INSERT INTO REPUESTO (id_repuesto, cantidad, descripcion, nombre, valor) values (5, 12, 'Llanta Timsun 90-90-18', 'Llanta', 115000)
INSERT INTO FACTURA (id_factura, descripcion_mano_obra, valor_mano_obra) values (1, 'se le cambio el aceite y se revisaron frenos', 10000)
INSERT INTO FACTURA (id_factura, descripcion_mano_obra, valor_mano_obra) values (2, 'tensión de cadena, carburación y calibrar aire', 22000)
INSERT INTO PERSONA(id_persona, apellidos, correo, direccion, nombre, telefono) values (1, 'Ramirez', 'ramirez1@gmail.com', 'cll #4', 'Raul', 0003344568)
INSERT INTO MOVIMIENTO(id_movimiento, fecha_ingreso,fecha_salida,placa,id_factura) values (1, '2008-11-11', '2008-11-12', 'loj567', 1)
INSERT INTO MECANICO(id_mecanico, id_persona, disponibilidad, especialidad, id_movimiento) values (1,1,true,'motocicletas',1)

